# tell travis we need a copy of docker running
sudo: required
services:
    - docker
before_install:
    - docker build -t nikunj/frontend -f Dockerfile.dev .
script:
    - docker run -e CI=true nikunj/frontend npm run test -- --coverage

deploy:
    provider: alsticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-809252609179"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

