# tell travis we need a copy of docker running
sudo: required
services:
    - docker
before_install:
    - docker build -t nikunj/frontend -f Dockerfile.dev .
script:
    - docker run -e CI=true nikunj/frontend npm run test -- --coverage

